name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
 build:
    env:
      DOCKER_USR: ${{ secrets.DOCKER_USR }}
      DOCKER_TKN: ${{ secrets.DOCKER_TKN }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login into Docker Account
      run: docker login -u $DOCKER_USR -p $DOCKER_TKN
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $DOCKER_USR/todo-cicd:${{ GITHUB.SHA }}
    - name: Push the Docker image
      run: docker push $DOCKER_USR/todo-cicd:${{ GITHUB.SHA }}

          
      

