name: Terraform CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
 deploy:
  runs-on: ubuntu-latest
  steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - uses: hashicorp/setup-terraform@v2.0.3
    - name: Init
      run: terraform init -backend-config="access_key="{{ secrets.AWS_ACC_KEY }} -backend-config="secret_key="{{ secrets.AWS_SECRET_KEY }} -backend-config="region=us-east-1"
      working-directory: ./infrastructure
      
    - name: Validate
      run: terraform validate
      working-directory: ./infrastructure
      
    - name: Plan
      run: terraform plan -out "planfile" tfvars=variables.tfvars
      working-directory: ./infrastructure

    - name: Apply
      run: echo "terraform apply planfile" tfvars=variables.tfvars
      working-directory: ./infrastructure
