name: Terraform CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
 deploy:
  runs-on: ubuntu-latest
  env:
    working-directory: ./infrastructure
  steps:
    - uses: hashicorp/setup-terraform@v2.0.3
    - name: Validate
      run: ls            
    - name: Plan
      run: terraform plan -out "planfile" 
      working-directory: ${{ env.working-directory }}

    - name: Apply
      run: echo "terraform apply planfile"
      working-directory: ${{ env.working-directory }}

