name: Terraform CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
 deploy:
  runs-on: ubuntu-latest
  steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Exchange secrets
      run: |
           sed -i 's|AWS_ACC_KEY|${{ secrets.AWS_ACC_KEY }}|g' variables.tfvars
           sed -i 's|AWS_SECRET_KEY|${{ secrets.AWS_SECRET_KEY }}|g' variables.tfvars    
      working-directory: ./infrastructure

    - name: Init
      run: terraform init -backend-config="access_key=${{ secrets.AWS_ACC_KEY }}" -backend-config="secret_key=${{ secrets.AWS_SECRET_KEY }}"
      working-directory: ./infrastructure

    - name: Watch variable
      run: cat variables.tfvars
      working-directory: ./infrastructure


    - name: Validate
      run: terraform validate
      working-directory: ./infrastructure
      
    - name: Plan
      run: terraform plan -out "planfile" -var-file=variables.tfvars
      working-directory: ./infrastructure

    - name: Apply
      run: terraform apply planfile
      working-directory: ./infrastructure
