name: Terraform CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
 deploy:
  runs-on: ubuntu-latest
  steps:
    - uses: hashicorp/setup-terraform@v2.0.3
    - name: Validate
      run: terraform validate ../infrastructure
    - name: Plan
      run: terraform plan -out "planfile" 
    - name: Apply
      run: terraform apply planfile
