name: Terraform CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
 deploy:
  runs-on: ubuntu-latest
  steps:
    - name: Check out code
      uses: actions/checkout@v2

    - uses: hashicorp/setup-terraform@v2.0.3
    - name: Write variables
      run: |
            variables="
            access_key     = \"${{ secrets.AWS_ACC_KEY }}\"
            secret_key     = \"${{ secrets.AWS_SECRET_KEY }}\"
            project_region = \"us-east-1\"
            cluster_name   = \"dendrogram_cluster\"
            type_of_nodes  = \"FARGATE\"
            iam_policy_arn = [
              \"arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy\"
            , \"arn:aws:iam::aws:policy/AWSCodeDeployRoleForECS\"
            ]
            task_list = {
            front_task = {
              name           = \"front-task\",
              service        = \"front-service\",
              image_uri      = \"422938382330.dkr.ecr.us-east-1.amazonaws.com/dendrogram-app:${FRONT_VERSION}\",
              container_port = 8080,
              host_port      = 8080,
              tg_port        = 80,
              protocol       = \"HTTP\",
              desired_count  = 1
            } 
            }"

            echo variables > ./variables.tfvars
    - name: Exchange secrets
      run: |
           sed -i 's/${{ secrets.AWS_ACC_KEY}}/${{ secrets.AWS_ACC_KEY}}/g' variables.tfvars
           sed -i 's/${{ secrets.AWS_SECRET_KEY}}/${{ secrets.AWS_SECRET_KEY}}/g' variables.tfvars

    
    - name: Init
      run: terraform init -backend-config="access_key=${{ secrets.AWS_ACC_KEY }}" -backend-config="secret_key=${{ secrets.AWS_SECRET_KEY }}"
      working-directory: ./infrastructure
      
    - name: Validate
      run: terraform validate
      working-directory: ./infrastructure
      
    - name: Plan
      run: terraform plan -out "planfile" -var-file=variables.tfvars
      working-directory: ./infrastructure

    - name: Apply
      run: echo "terraform apply planfile" -var-file=variables.tfvars
      working-directory: ./infrastructure
