name: Deploy Infrastructure
on:
  push:
    branches:
      - master
jobs:
 deploy:
  runs-on: ubuntu-latest
  steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - uses: hashicorp/setup-terraform@v2.0.3
    - name: Validate
      run: terraform validate
      working-directory: /infrastructure
      
    - name: Plan
      run: terraform plan -out "planfile" 
      working-directory: /infrastructure

    - name: Apply
      run: echo "terraform apply planfile"
      working-directory: /infrastructure
